// Categories and Subcategories
export const categories = [
  {
    id: 1,
    name: "Marble",
    slug: "marble",
    subcategories: [
      { id: "sub-101", name: "Green Marble", slug: "green-marble" },
      { id: "sub-102", name: "Fantasy Brown Marble", slug: "fantasy-brown-marble" },
      { id: "sub-103", name: "Bhenslana Black Marble", slug: "bhenslana-black-marble" },
      { id: "sub-104", name: "Udaipur Pink Marble", slug: "udaipur-pink-marble" }
    ]
  },
  {
    id: 2,
    name: "Granite",
    slug: "granite",
    subcategories: [
      { id: "sub-201", name: "Absolute Black Granite", slug: "absolute-black-granite" },
      { id: "sub-202", name: "Black Galaxy Granite", slug: "black-galaxy-granite" },
      { id: "sub-203", name: "Kashmir White Granite", slug: "kashmir-white-granite" },
      { id: "sub-204", name: "Colonial Cream Granite", slug: "colonial-cream-granite" },
      { id: "sub-205", name: "Sira Grey Granite", slug: "sira-grey-granite" },
      { id: "sub-206", name: "Sadarahalli Grey Granite", slug: "sadarahalli-grey-granite" },
      { id: "sub-207", name: "Crystal Blue Granite", slug: "crystal-blue-granite" },
      { id: "sub-208", name: "Crystal Yellow Granite", slug: "crystal-yellow-granite" },
      { id: "sub-209", name: "Crystal Brown Granite", slug: "crystal-brown-granite" },
      { id: "sub-210", name: "P White Granite", slug: "p-white-granite" },
      { id: "sub-211", name: "Rajasthan Black Granite", slug: "rajasthan-black-granite" },
      { id: "sub-212", name: "Rosy Pink Granite", slug: "rosy-pink-granite" },
      { id: "sub-213", name: "Chima Pink Granite", slug: "chima-pink-granite" },
      { id: "sub-214", name: "Lakha Red Granite", slug: "lakha-red-granite" },
      { id: "sub-215", name: "Gem Red Granite", slug: "gem-red-granite" },
      { id: "sub-216", name: "Imperial Red Granite", slug: "imperial-red-granite" }
    ]
  },
  {
    id: 3,
    name: "Sandstone",
    slug: "sandstone",
    subcategories: [
      { id: "sub-301", name: "Red Sandstone", slug: "red-sandstone" },
      { id: "sub-302", name: "Beige Sandstone", slug: "beige-sandstone" },
      { id: "sub-303", name: "Gwalior Mint Sandstone", slug: "gwalior-mint-sandstone" },
      { id: "sub-304", name: "Teak Sandstone", slug: "teak-sandstone" },
      { id: "sub-305", name: "Rainbow Sandstone", slug: "rainbow-sandstone" },
      { id: "sub-306", name: "Pink Sandstone", slug: "pink-sandstone" }
    ]
  },
  {
    id: 4,
    name: "Limestone",
    slug: "limestone",
    subcategories: [
      { id: "sub-401", name: "Jaisalmer Yellow Limestone", slug: "jaisalmer-yellow-limestone" },
      { id: "sub-402", name: "Kota Limestone", slug: "kota-limestone" },
      { id: "sub-403", name: "Bijolia Grey Limestone", slug: "bijolia-grey-limestone" },
      { id: "sub-404", name: "Chittor Black Limestone", slug: "chittor-black-limestone" }
    ]
  },
  {
    id: 5,
    name: "Basalt Stone",
    slug: "basalt-stone",
    subcategories: [
      { id: "sub-701", name: "Basalt", slug: "basalt" }
    ]
  }
];

// Helper to get category and subcategory for products
const getCategory = (catSlug) => categories.find(c => c.slug === catSlug);
const getSubcategory = (catSlug, subSlug) => {
  const cat = getCategory(catSlug);
  return cat?.subcategories.find(s => s.slug === subSlug);
};

// All product definitions
const productDefinitions = [
  // Marble
  {
    id: 101,
    name: "Green Marble",
    slug: "green-marble",
    categorySlug: "marble",
    subcategorySlug: "green-marble",
    image: "Green marble.png",
    images: ["Green marble.png"],
    category: getCategory("marble"),
    subcategory: getSubcategory("marble", "green-marble"),
    description: "Green Marble is a beautiful natural stone with a rich green base and elegant white or gray veining, perfect for creating sophisticated interiors.",
    features: ["Rich green base color", "Elegant white/gray veining", "Timeless appearance", "Durable and long-lasting"],
    benefits: ["Adds natural beauty to interiors", "Perfect for both classic and modern designs", "Increases property value", "Easy to maintain"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Floor tiles", "Wall cladding", "Fireplace surrounds"],
    maintenance: "Clean with pH-neutral cleaner, avoid harsh chemicals, wipe spills immediately, seal annually.",
    whyChoose: "Green Marble offers a unique, elegant look that brings natural beauty to any space.",
    seoTitle: "Green Marble | Elegant Natural Stone",
    metaDescription: "Discover Green Marble. Rich green base with elegant veining, perfect for sophisticated interiors and luxury designs.",
    imageAlt: "Elegant Green Marble with natural veining",
    tags: ["Green Marble", "Marble", "Natural Stone", "Luxury Stone"]
  },
  {
    id: 102,
    name: "Fantasy Brown Marble",
    slug: "fantasy-brown-marble",
    categorySlug: "marble",
    subcategorySlug: "fantasy-brown-marble",
    image: "Rainforest brown.png",
    images: ["Rainforest brown.png"],
    category: getCategory("marble"),
    subcategory: getSubcategory("marble", "fantasy-brown-marble"),
    description: "Fantasy Brown Marble is a stunning stone with warm brown tones and intricate patterns that create a fantasy-like appearance.",
    features: ["Warm brown base", "Intricate natural patterns", "Unique and exotic look", "High-quality material"],
    benefits: ["Creates striking focal points", "Perfect for luxury projects", "Unique natural variations", "Timeless beauty"],
    applications: ["Kitchen islands", "Feature walls", "Bathroom surrounds", "Flooring", "Tabletops"],
    maintenance: "Clean with pH-neutral cleaner, avoid harsh chemicals, wipe spills immediately, seal annually.",
    whyChoose: "Fantasy Brown Marble brings an exotic, fantasy-like beauty to any interior space.",
    seoTitle: "Fantasy Brown Marble | Exotic Natural Stone",
    metaDescription: "Explore Fantasy Brown Marble. Warm brown tones with intricate patterns, perfect for creating exotic and luxurious interiors.",
    imageAlt: "Exotic Fantasy Brown Marble with intricate patterns",
    tags: ["Fantasy Brown Marble", "Marble", "Exotic Stone", "Luxury Stone"]
  },
  {
    id: 103,
    name: "Bhenslana Black Marble",
    slug: "bhenslana-black-marble",
    categorySlug: "marble",
    subcategorySlug: "bhenslana-black-marble",
    image: "Black Granite.png",
    images: ["Black Granite.png"],
    category: getCategory("marble"),
    subcategory: getSubcategory("marble", "bhenslana-black-marble"),
    description: "Bhenslana Black Marble is a deep black marble with subtle white veining, perfect for creating bold, dramatic interiors.",
    features: ["Deep black base", "Subtle white veining", "Bold and dramatic look", "Premium quality"],
    benefits: ["Creates stunning contrast", "Perfect for modern designs", "Luxurious appearance", "High durability"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Feature walls", "Flooring", "Staircases"],
    maintenance: "Clean with pH-neutral cleaner, avoid harsh chemicals, wipe spills immediately, seal annually.",
    whyChoose: "Bhenslana Black Marble offers a bold, dramatic look that makes a strong statement.",
    seoTitle: "Bhenslana Black Marble | Bold Dramatic Stone",
    metaDescription: "Discover Bhenslana Black Marble. Deep black base with subtle white veining, perfect for bold and dramatic interiors.",
    imageAlt: "Dramatic Bhenslana Black Marble with subtle white veining",
    tags: ["Bhenslana Black Marble", "Black Marble", "Luxury Stone", "Dramatic Stone"]
  },
  {
    id: 104,
    name: "Udaipur Pink Marble",
    slug: "udaipur-pink-marble",
    categorySlug: "marble",
    subcategorySlug: "udaipur-pink-marble",
    image: "Makrana white marble.png",
    images: ["Makrana white marble.png"],
    category: getCategory("marble"),
    subcategory: getSubcategory("marble", "udaipur-pink-marble"),
    description: "Udaipur Pink Marble is a beautiful pink marble quarried in Udaipur, Rajasthan, known for its soft pink color and elegant appearance.",
    features: ["Soft pink base", "Subtle natural veining", "Elegant and timeless", "Premium Indian marble"],
    benefits: ["Adds warmth to interiors", "Perfect for traditional designs", "Unique and rare", "Increases property value"],
    applications: ["Flooring", "Wall cladding", "Temple construction", "Decorative items", "Tabletops"],
    maintenance: "Clean with pH-neutral cleaner, avoid harsh chemicals, wipe spills immediately, seal annually.",
    whyChoose: "Udaipur Pink Marble offers a unique, elegant pink hue that brings warmth to any space.",
    seoTitle: "Udaipur Pink Marble | Elegant Pink Stone",
    metaDescription: "Explore Udaipur Pink Marble. Soft pink base with elegant veining, perfect for traditional and sophisticated interiors.",
    imageAlt: "Elegant Udaipur Pink Marble with soft pink hue",
    tags: ["Udaipur Pink Marble", "Pink Marble", "Indian Marble", "Luxury Stone"]
  },

  // Granite
  {
    id: 201,
    name: "Absolute Black Granite",
    slug: "absolute-black-granite",
    categorySlug: "granite",
    subcategorySlug: "absolute-black-granite",
    image: "Black Granite.png",
    images: ["Black Granite.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "absolute-black-granite"),
    description: "Absolute Black Granite is a premium granite with a deep, uniform black color, perfect for creating sleek, modern interiors.",
    features: ["Deep uniform black", "Highly polished finish", "Extremely durable", "Resistant to scratches"],
    benefits: ["Sleek modern appearance", "Low maintenance", "Long-lasting durability", "Perfect for high-traffic areas"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Flooring", "Staircases", "Tabletops"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "Absolute Black Granite offers a sleek, modern look with exceptional durability.",
    seoTitle: "Absolute Black Granite | Sleek Modern Stone",
    metaDescription: "Discover Absolute Black Granite. Deep uniform black, perfect for sleek modern interiors and high-traffic areas.",
    imageAlt: "Sleek Absolute Black Granite with uniform black color",
    tags: ["Absolute Black Granite", "Black Granite", "Modern Stone", "Durable Stone"]
  },
  {
    id: 202,
    name: "Black Galaxy Granite",
    slug: "black-galaxy-granite",
    categorySlug: "granite",
    subcategorySlug: "black-galaxy-granite",
    image: "Black-texure Granite.png",
    images: ["Black-texure Granite.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "black-galaxy-granite"),
    description: "Black Galaxy Granite is a stunning granite with a black base and sparkling golden flecks, resembling a starry galaxy.",
    features: ["Black base with golden flecks", "Sparkling galaxy-like appearance", "Highly durable", "Unique and exotic"],
    benefits: ["Creates stunning focal points", "Perfect for luxury designs", "High durability", "Low maintenance"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Feature walls", "Tabletops", "Bar tops"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "Black Galaxy Granite offers a unique, sparkling appearance that resembles a starry night sky.",
    seoTitle: "Black Galaxy Granite | Sparkling Exotic Stone",
    metaDescription: "Explore Black Galaxy Granite. Black base with sparkling golden flecks, perfect for luxurious and exotic interiors.",
    imageAlt: "Sparkling Black Galaxy Granite with golden flecks",
    tags: ["Black Galaxy Granite", "Granite", "Exotic Stone", "Luxury Stone"]
  },
  {
    id: 203,
    name: "Kashmir White Granite",
    slug: "kashmir-white-granite",
    categorySlug: "granite",
    subcategorySlug: "kashmir-white-granite",
    image: "Gray granite.png",
    images: ["Gray granite.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "kashmir-white-granite"),
    description: "Kashmir White Granite is a beautiful white granite with gray and black specks, perfect for creating bright, elegant interiors.",
    features: ["White base with gray/black specks", "Bright and elegant appearance", "Highly durable", "Versatile design"],
    benefits: ["Brightens up interiors", "Perfect for both classic and modern designs", "Low maintenance", "High durability"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Flooring", "Wall cladding", "Tabletops"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "Kashmir White Granite offers a bright, elegant look that complements any design style.",
    seoTitle: "Kashmir White Granite | Bright Elegant Stone",
    metaDescription: "Discover Kashmir White Granite. White base with gray and black specks, perfect for bright and elegant interiors.",
    imageAlt: "Elegant Kashmir White Granite with gray and black specks",
    tags: ["Kashmir White Granite", "White Granite", "Granite", "Elegant Stone"]
  },
  {
    id: 204,
    name: "Colonial Cream Granite",
    slug: "colonial-cream-granite",
    categorySlug: "granite",
    subcategorySlug: "colonial-cream-granite",
    image: "Granite Polished charcoal.png",
    images: ["Granite Polished charcoal.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "colonial-cream-granite"),
    description: "Colonial Cream Granite is a warm cream-colored granite with subtle variations, perfect for creating cozy, inviting interiors.",
    features: ["Warm cream base", "Subtle natural variations", "Timeless appearance", "Highly durable"],
    benefits: ["Adds warmth to interiors", "Perfect for traditional designs", "Low maintenance", "High durability"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Flooring", "Wall cladding", "Fireplace surrounds"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "Colonial Cream Granite offers a warm, timeless look that creates cozy interiors.",
    seoTitle: "Colonial Cream Granite | Warm Timeless Stone",
    metaDescription: "Explore Colonial Cream Granite. Warm cream base with subtle variations, perfect for cozy and inviting interiors.",
    imageAlt: "Warm Colonial Cream Granite with subtle variations",
    tags: ["Colonial Cream Granite", "Cream Granite", "Granite", "Warm Stone"]
  },
  {
    id: 205,
    name: "Sira Grey Granite",
    slug: "sira-grey-granite",
    categorySlug: "granite",
    subcategorySlug: "sira-grey-granite",
    image: "Gray granite.png",
    images: ["Gray granite.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "sira-grey-granite"),
    description: "Sira Grey Granite is a sophisticated grey granite with natural patterns, perfect for creating modern, elegant interiors.",
    features: ["Sophisticated grey base", "Natural patterns", "Modern appearance", "Highly durable"],
    benefits: ["Perfect for modern designs", "Versatile and elegant", "Low maintenance", "High durability"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Flooring", "Wall cladding", "Tabletops"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "Sira Grey Granite offers a sophisticated, modern look that complements any design.",
    seoTitle: "Sira Grey Granite | Sophisticated Modern Stone",
    metaDescription: "Discover Sira Grey Granite. Sophisticated grey base with natural patterns, perfect for modern and elegant interiors.",
    imageAlt: "Sophisticated Sira Grey Granite with natural patterns",
    tags: ["Sira Grey Granite", "Grey Granite", "Granite", "Modern Stone"]
  },
  {
    id: 206,
    name: "Sadarahalli Grey Granite",
    slug: "sadarahalli-grey-granite",
    categorySlug: "granite",
    subcategorySlug: "sadarahalli-grey-granite",
    image: "Gray granite.png",
    images: ["Gray granite.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "sadarahalli-grey-granite"),
    description: "Sadarahalli Grey Granite is a popular grey granite quarried in Karnataka, known for its consistent grey color and durability.",
    features: ["Consistent grey base", "Highly durable", "Versatile application", "Indian granite"],
    benefits: ["Perfect for both residential and commercial projects", "Low maintenance", "High durability", "Affordable luxury"],
    applications: ["Flooring", "Kitchen countertops", "Wall cladding", "Staircases", "Paving"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "Sadarahalli Grey Granite offers consistent quality and durability at an affordable price.",
    seoTitle: "Sadarahalli Grey Granite | Consistent Durable Stone",
    metaDescription: "Explore Sadarahalli Grey Granite. Consistent grey base, perfect for both residential and commercial projects.",
    imageAlt: "Consistent Sadarahalli Grey Granite",
    tags: ["Sadarahalli Grey Granite", "Grey Granite", "Indian Granite", "Durable Stone"]
  },
  {
    id: 207,
    name: "Crystal Blue Granite",
    slug: "crystal-blue-granite",
    categorySlug: "granite",
    subcategorySlug: "crystal-blue-granite",
    image: "Blue Agate Basin.png",
    images: ["Blue Agate Basin.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "crystal-blue-granite"),
    description: "Crystal Blue Granite is a stunning granite with blue tones and crystal-like patterns, perfect for creating unique interiors.",
    features: ["Blue tones with crystal patterns", "Unique and exotic", "Highly durable", "Eye-catching appearance"],
    benefits: ["Creates unique focal points", "Perfect for luxury designs", "Low maintenance", "High durability"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Feature walls", "Tabletops", "Bar tops"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "Crystal Blue Granite offers a unique, exotic look that stands out in any space.",
    seoTitle: "Crystal Blue Granite | Unique Exotic Stone",
    metaDescription: "Discover Crystal Blue Granite. Blue tones with crystal-like patterns, perfect for unique and exotic interiors.",
    imageAlt: "Unique Crystal Blue Granite with blue tones and crystal patterns",
    tags: ["Crystal Blue Granite", "Blue Granite", "Granite", "Exotic Stone"]
  },
  {
    id: 208,
    name: "Crystal Yellow Granite",
    slug: "crystal-yellow-granite",
    categorySlug: "granite",
    subcategorySlug: "crystal-yellow-granite",
    image: "Polished granite.png",
    images: ["Polished granite.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "crystal-yellow-granite"),
    description: "Crystal Yellow Granite is a warm yellow granite with crystal-like patterns, perfect for creating bright, cheerful interiors.",
    features: ["Warm yellow base", "Crystal-like patterns", "Bright and cheerful", "Highly durable"],
    benefits: ["Brightens up interiors", "Perfect for warm designs", "Low maintenance", "High durability"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Flooring", "Wall cladding", "Tabletops"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "Crystal Yellow Granite offers a bright, cheerful look that warms up any space.",
    seoTitle: "Crystal Yellow Granite | Bright Cheerful Stone",
    metaDescription: "Explore Crystal Yellow Granite. Warm yellow base with crystal-like patterns, perfect for bright and cheerful interiors.",
    imageAlt: "Bright Crystal Yellow Granite with crystal-like patterns",
    tags: ["Crystal Yellow Granite", "Yellow Granite", "Granite", "Warm Stone"]
  },
  {
    id: 209,
    name: "Crystal Brown Granite",
    slug: "crystal-brown-granite",
    categorySlug: "granite",
    subcategorySlug: "crystal-brown-granite",
    image: "Rustic brown stone texture close-up.png",
    images: ["Rustic brown stone texture close-up.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "crystal-brown-granite"),
    description: "Crystal Brown Granite is a rich brown granite with crystal-like patterns, perfect for creating warm, inviting interiors.",
    features: ["Rich brown base", "Crystal-like patterns", "Warm and inviting", "Highly durable"],
    benefits: ["Adds warmth to interiors", "Perfect for cozy designs", "Low maintenance", "High durability"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Flooring", "Wall cladding", "Fireplace surrounds"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "Crystal Brown Granite offers a warm, inviting look that creates cozy interiors.",
    seoTitle: "Crystal Brown Granite | Warm Inviting Stone",
    metaDescription: "Discover Crystal Brown Granite. Rich brown base with crystal-like patterns, perfect for warm and inviting interiors.",
    imageAlt: "Warm Crystal Brown Granite with crystal-like patterns",
    tags: ["Crystal Brown Granite", "Brown Granite", "Granite", "Warm Stone"]
  },
  {
    id: 210,
    name: "P White Granite",
    slug: "p-white-granite",
    categorySlug: "granite",
    subcategorySlug: "p-white-granite",
    image: "Gray granite.png",
    images: ["Gray granite.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "p-white-granite"),
    description: "P White Granite is a beautiful white granite with subtle grey specks, perfect for creating bright, clean interiors.",
    features: ["White base with subtle grey specks", "Bright and clean appearance", "Highly durable", "Versatile design"],
    benefits: ["Brightens up interiors", "Perfect for modern designs", "Low maintenance", "High durability"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Flooring", "Wall cladding", "Tabletops"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "P White Granite offers a bright, clean look that complements any modern design.",
    seoTitle: "P White Granite | Bright Clean Stone",
    metaDescription: "Explore P White Granite. White base with subtle grey specks, perfect for bright and clean interiors.",
    imageAlt: "Bright P White Granite with subtle grey specks",
    tags: ["P White Granite", "White Granite", "Granite", "Modern Stone"]
  },
  {
    id: 211,
    name: "Rajasthan Black Granite",
    slug: "rajasthan-black-granite",
    categorySlug: "granite",
    subcategorySlug: "rajasthan-black-granite",
    image: "Black Granite.png",
    images: ["Black Granite.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "rajasthan-black-granite"),
    description: "Rajasthan Black Granite is a premium black granite quarried in Rajasthan, known for its deep black color and durability.",
    features: ["Deep black base", "Premium Indian granite", "Highly durable", "Consistent quality"],
    benefits: ["Perfect for luxury designs", "Low maintenance", "High durability", "Adds sophistication"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Flooring", "Staircases", "Tabletops"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "Rajasthan Black Granite offers premium quality and a deep black color that adds sophistication.",
    seoTitle: "Rajasthan Black Granite | Premium Indian Stone",
    metaDescription: "Discover Rajasthan Black Granite. Deep black base, premium Indian granite, perfect for luxurious interiors.",
    imageAlt: "Premium Rajasthan Black Granite with deep black color",
    tags: ["Rajasthan Black Granite", "Black Granite", "Indian Granite", "Premium Stone"]
  },
  {
    id: 212,
    name: "Rosy Pink Granite",
    slug: "rosy-pink-granite",
    categorySlug: "granite",
    subcategorySlug: "rosy-pink-granite",
    image: "Red new granite.png",
    images: ["Red new granite.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "rosy-pink-granite"),
    description: "Rosy Pink Granite is a beautiful pink granite with rosy tones, perfect for creating warm, feminine interiors.",
    features: ["Rosy pink base", "Warm and feminine", "Unique appearance", "Highly durable"],
    benefits: ["Adds warmth to interiors", "Perfect for unique designs", "Low maintenance", "High durability"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Tabletops", "Decorative items", "Feature walls"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "Rosy Pink Granite offers a unique, warm pink hue that adds femininity to any space.",
    seoTitle: "Rosy Pink Granite | Warm Feminine Stone",
    metaDescription: "Explore Rosy Pink Granite. Rosy pink base, perfect for warm and feminine interiors.",
    imageAlt: "Warm Rosy Pink Granite with rosy hue",
    tags: ["Rosy Pink Granite", "Pink Granite", "Granite", "Warm Stone"]
  },
  {
    id: 213,
    name: "Chima Pink Granite",
    slug: "chima-pink-granite",
    categorySlug: "granite",
    subcategorySlug: "chima-pink-granite",
    image: "Red granite texture.png",
    images: ["Red granite texture.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "chima-pink-granite"),
    description: "Chima Pink Granite is a unique pink granite with distinctive patterns, perfect for creating eye-catching interiors.",
    features: ["Pink base with distinctive patterns", "Unique and eye-catching", "Highly durable", "Versatile design"],
    benefits: ["Creates eye-catching focal points", "Perfect for unique designs", "Low maintenance", "High durability"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Feature walls", "Tabletops", "Bar tops"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "Chima Pink Granite offers a unique, eye-catching look that stands out in any space.",
    seoTitle: "Chima Pink Granite | Unique Eye-catching Stone",
    metaDescription: "Discover Chima Pink Granite. Unique pink base with distinctive patterns, perfect for eye-catching interiors.",
    imageAlt: "Unique Chima Pink Granite with distinctive patterns",
    tags: ["Chima Pink Granite", "Pink Granite", "Granite", "Unique Stone"]
  },
  {
    id: 214,
    name: "Lakha Red Granite",
    slug: "lakha-red-granite",
    categorySlug: "granite",
    subcategorySlug: "lakha-red-granite",
    image: "Shiny red granite.png",
    images: ["Shiny red granite.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "lakha-red-granite"),
    description: "Lakha Red Granite is a vibrant red granite quarried in Rajasthan, known for its deep red color and durability.",
    features: ["Deep vibrant red base", "Premium Indian granite", "Highly durable", "Striking appearance"],
    benefits: ["Creates striking focal points", "Perfect for bold designs", "Low maintenance", "High durability"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Feature walls", "Flooring", "Tabletops"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "Lakha Red Granite offers a vibrant, striking look that makes a bold statement.",
    seoTitle: "Lakha Red Granite | Vibrant Bold Stone",
    metaDescription: "Explore Lakha Red Granite. Deep vibrant red base, perfect for bold and striking interiors.",
    imageAlt: "Vibrant Lakha Red Granite with deep red color",
    tags: ["Lakha Red Granite", "Red Granite", "Indian Granite", "Bold Stone"]
  },
  {
    id: 215,
    name: "Gem Red Granite",
    slug: "gem-red-granite",
    categorySlug: "granite",
    subcategorySlug: "gem-red-granite",
    image: "Red granite texture.png",
    images: ["Red granite texture.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "gem-red-granite"),
    description: "Gem Red Granite is a rich red granite with gem-like patterns, perfect for creating luxurious interiors.",
    features: ["Rich red base with gem-like patterns", "Luxurious appearance", "Highly durable", "Unique and exotic"],
    benefits: ["Adds luxury to interiors", "Perfect for high-end designs", "Low maintenance", "High durability"],
    applications: ["Kitchen countertops", "Bathroom vanities", "Feature walls", "Tabletops", "Bar tops"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "Gem Red Granite offers a luxurious, gem-like appearance that elevates any space.",
    seoTitle: "Gem Red Granite | Luxurious Gem-like Stone",
    metaDescription: "Discover Gem Red Granite. Rich red base with gem-like patterns, perfect for luxurious interiors.",
    imageAlt: "Luxurious Gem Red Granite with gem-like patterns",
    tags: ["Gem Red Granite", "Red Granite", "Granite", "Luxury Stone"]
  },
  {
    id: 216,
    name: "Imperial Red Granite",
    slug: "imperial-red-granite",
    categorySlug: "granite",
    subcategorySlug: "imperial-red-granite",
    image: "Red granite texture.png",
    images: ["Red granite texture.png"],
    category: getCategory("granite"),
    subcategory: getSubcategory("granite", "imperial-red-granite"),
    description: "Imperial Red Granite is a majestic red granite with imperial patterns, perfect for creating grand, luxurious interiors.",
    features: ["Majestic red base", "Imperial patterns", "Grand and luxurious", "Highly durable"],
    benefits: ["Creates grand focal points", "Perfect for luxury projects", "Low maintenance", "High durability"],
    applications: ["Kitchen islands", "Feature walls", "Bathroom surrounds", "Flooring", "Tabletops"],
    maintenance: "Clean with mild soap and water, avoid harsh chemicals, wipe spills immediately.",
    whyChoose: "Imperial Red Granite offers a grand, majestic look that creates luxurious interiors.",
    seoTitle: "Imperial Red Granite | Grand Majestic Stone",
    metaDescription: "Explore Imperial Red Granite. Majestic red base with imperial patterns, perfect for grand and luxurious interiors.",
    imageAlt: "Grand Imperial Red Granite with imperial patterns",
    tags: ["Imperial Red Granite", "Red Granite", "Granite", "Luxury Stone"]
  },

  // Sandstone
  {
    id: 301,
    name: "Red Sandstone",
    slug: "red-sandstone",
    categorySlug: "sandstone",
    subcategorySlug: "red-sandstone",
    image: "Reddish sandstone slabs in sunlight.png",
    images: ["Reddish sandstone slabs in sunlight.png"],
    category: getCategory("sandstone"),
    subcategory: getSubcategory("sandstone", "red-sandstone"),
    description: "Red Sandstone is a classic sandstone with a rich red color, perfect for both interior and exterior applications.",
    features: ["Rich red base", "Classic appearance", "Weather-resistant", "Versatile"],
    benefits: ["Perfect for both indoor and outdoor use", "Timeless look", "Durable and weather-resistant", "Easy to work with"],
    applications: ["Flooring", "Wall cladding", "Paving", "Architectural elements", "Decorative items"],
    maintenance: "Clean with mild soap and water, seal periodically for outdoor use.",
    whyChoose: "Red Sandstone offers a classic, timeless look that works for both interior and exterior projects.",
    seoTitle: "Red Sandstone | Classic Timeless Stone",
    metaDescription: "Discover Red Sandstone. Rich red base, perfect for both interior and exterior applications.",
    imageAlt: "Classic Red Sandstone with rich red color",
    tags: ["Red Sandstone", "Sandstone", "Natural Stone", "Outdoor Stone"]
  },
  {
    id: 302, name: "Beige Sandstone", slug: "beige-sandstone", categorySlug: "sandstone", subcategorySlug: "beige-sandstone",
    image: "Naturally patterned sandstone slab.png", images: ["Naturally patterned sandstone slab.png"],
    category: getCategory("sandstone"), subcategory: getSubcategory("sandstone", "beige-sandstone"),
    description: "Beige Sandstone is a warm beige sandstone with natural patterns, perfect for creating cozy interiors.",
    features: ["Warm beige base", "Natural patterns", "Cozy appearance", "Versatile"],
    benefits: ["Adds warmth to interiors", "Perfect for cozy designs", "Durable", "Easy to maintain"],
    applications: ["Flooring", "Wall cladding", "Fireplace surrounds", "Decorative items", "Paving"],
    maintenance: "Clean with mild soap and water, seal periodically for outdoor use.",
    whyChoose: "Beige Sandstone offers a warm, cozy look that creates inviting interiors.",
    seoTitle: "Beige Sandstone | Warm Cozy Stone",
    metaDescription: "Explore Beige Sandstone. Warm beige base with natural patterns, perfect for cozy interiors.",
    imageAlt: "Warm Beige Sandstone with natural patterns",
    tags: ["Beige Sandstone", "Sandstone", "Natural Stone", "Warm Stone"]
  },
  {
    id: 303, name: "Gwalior Mint Sandstone", slug: "gwalior-mint-sandstone", categorySlug: "sandstone", subcategorySlug: "gwalior-mint-sandstone",
    image: "Green granit.png", images: ["Green granit.png"],
    category: getCategory("sandstone"), subcategory: getSubcategory("sandstone", "gwalior-mint-sandstone"),
    description: "Gwalior Mint Sandstone is a unique mint green sandstone quarried in Gwalior, perfect for creating fresh interiors.",
    features: ["Mint green base", "Unique and fresh", "Indian sandstone", "Durable"],
    benefits: ["Creates fresh interiors", "Perfect for unique designs", "Durable", "Versatile"],
    applications: ["Flooring", "Wall cladding", "Decorative items", "Paving", "Architectural elements"],
    maintenance: "Clean with mild soap and water, seal periodically for outdoor use.",
    whyChoose: "Gwalior Mint Sandstone offers a unique, fresh mint green hue that stands out.",
    seoTitle: "Gwalior Mint Sandstone | Unique Fresh Stone",
    metaDescription: "Discover Gwalior Mint Sandstone. Unique mint green base, perfect for fresh and unique interiors.",
    imageAlt: "Unique Gwalior Mint Sandstone with mint green hue",
    tags: ["Gwalior Mint Sandstone", "Sandstone", "Natural Stone", "Unique Stone"]
  },
  {
    id: 304, name: "Teak Sandstone", slug: "teak-sandstone", categorySlug: "sandstone", subcategorySlug: "teak-sandstone",
    image: "Rustic brown stone texture close-up.png", images: ["Rustic brown stone texture close-up.png"],
    category: getCategory("sandstone"), subcategory: getSubcategory("sandstone", "teak-sandstone"),
    description: "Teak Sandstone is a warm brown sandstone that resembles teak wood, perfect for creating natural interiors.",
    features: ["Warm brown base", "Wood-like appearance", "Natural look", "Durable"],
    benefits: ["Creates natural interiors", "Perfect for rustic designs", "Durable", "Versatile"],
    applications: ["Flooring", "Wall cladding", "Paving", "Decorative items", "Furniture"],
    maintenance: "Clean with mild soap and water, seal periodically for outdoor use.",
    whyChoose: "Teak Sandstone offers a natural, wood-like appearance that creates warm interiors.",
    seoTitle: "Teak Sandstone | Natural Wood-like Stone",
    metaDescription: "Explore Teak Sandstone. Warm brown base with wood-like appearance, perfect for natural interiors.",
    imageAlt: "Natural Teak Sandstone with wood-like appearance",
    tags: ["Teak Sandstone", "Sandstone", "Natural Stone", "Rustic Stone"]
  },
  {
    id: 305, name: "Rainbow Sandstone", slug: "rainbow-sandstone", categorySlug: "sandstone", subcategorySlug: "rainbow-sandstone",
    image: "Colored Marble.png", images: ["Colored Marble.png"],
    category: getCategory("sandstone"), subcategory: getSubcategory("sandstone", "rainbow-sandstone"),
    description: "Rainbow Sandstone is a stunning sandstone with rainbow-like color variations, perfect for creating vibrant interiors.",
    features: ["Rainbow-like color variations", "Stunning and vibrant", "Unique patterns", "Durable"],
    benefits: ["Creates vibrant focal points", "Perfect for unique designs", "Durable", "Versatile"],
    applications: ["Feature walls", "Flooring", "Decorative items", "Paving", "Architectural elements"],
    maintenance: "Clean with mild soap and water, seal periodically for outdoor use.",
    whyChoose: "Rainbow Sandstone offers a stunning, vibrant look with rainbow-like color variations.",
    seoTitle: "Rainbow Sandstone | Stunning Vibrant Stone",
    metaDescription: "Discover Rainbow Sandstone. Rainbow-like color variations, perfect for vibrant and unique interiors.",
    imageAlt: "Stunning Rainbow Sandstone with rainbow-like color variations",
    tags: ["Rainbow Sandstone", "Sandstone", "Natural Stone", "Vibrant Stone"]
  },
  {
    id: 306, name: "Pink Sandstone", slug: "pink-sandstone", categorySlug: "sandstone", subcategorySlug: "pink-sandstone",
    image: "Reddish sandstone slabs in sunlight.png", images: ["Reddish sandstone slabs in sunlight.png"],
    category: getCategory("sandstone"), subcategory: getSubcategory("sandstone", "pink-sandstone"),
    description: "Pink Sandstone is a beautiful pink sandstone, perfect for creating soft, elegant interiors.",
    features: ["Soft pink base", "Elegant appearance", "Soft and feminine", "Durable"],
    benefits: ["Adds elegance to interiors", "Perfect for soft designs", "Durable", "Versatile"],
    applications: ["Flooring", "Wall cladding", "Decorative items", "Paving", "Architectural elements"],
    maintenance: "Clean with mild soap and water, seal periodically for outdoor use.",
    whyChoose: "Pink Sandstone offers a soft, elegant look that creates beautiful interiors.",
    seoTitle: "Pink Sandstone | Soft Elegant Stone",
    metaDescription: "Explore Pink Sandstone. Soft pink base, perfect for soft and elegant interiors.",
    imageAlt: "Soft Pink Sandstone with elegant appearance",
    tags: ["Pink Sandstone", "Sandstone", "Natural Stone", "Elegant Stone"]
  },

  // Limestone
  {
    id: 401, name: "Jaisalmer Yellow Limestone", slug: "jaisalmer-yellow-limestone", categorySlug: "limestone", subcategorySlug: "jaisalmer-yellow-limestone",
    image: "Limestone-yellow-black.png", images: ["Limestone-yellow-black.png"],
    category: getCategory("limestone"), subcategory: getSubcategory("limestone", "jaisalmer-yellow-limestone"),
    description: "Jaisalmer Yellow Limestone is a warm yellow limestone quarried in Jaisalmer, Rajasthan, perfect for creating sunny interiors.",
    features: ["Warm yellow base", "Indian limestone", "Timeless appearance", "Durable"],
    benefits: ["Brightens up interiors", "Perfect for traditional designs", "Durable", "Versatile"],
    applications: ["Flooring", "Wall cladding", "Paving", "Architectural elements", "Decorative items"],
    maintenance: "Clean with mild soap and water, seal periodically for outdoor use.",
    whyChoose: "Jaisalmer Yellow Limestone offers a warm, sunny look that brightens up any space.",
    seoTitle: "Jaisalmer Yellow Limestone | Warm Sunny Stone",
    metaDescription: "Discover Jaisalmer Yellow Limestone. Warm yellow base, perfect for sunny and traditional interiors.",
    imageAlt: "Warm Jaisalmer Yellow Limestone with yellow hue",
    tags: ["Jaisalmer Yellow Limestone", "Limestone", "Natural Stone", "Indian Stone"]
  },
  {
    id: 402, name: "Kota Limestone", slug: "kota-limestone", categorySlug: "limestone", subcategorySlug: "kota-limestone",
    image: "Limestone.png", images: ["Limestone.png"],
    category: getCategory("limestone"), subcategory: getSubcategory("limestone", "kota-limestone"),
    description: "Kota Limestone is a popular limestone quarried in Kota, Rajasthan, known for its durability and affordability.",
    features: ["Grey/beige base", "Highly durable", "Affordable luxury", "Indian limestone"],
    benefits: ["Perfect for both residential and commercial projects", "Low maintenance", "High durability", "Affordable"],
    applications: ["Flooring", "Wall cladding", "Paving", "Staircases", "Tabletops"],
    maintenance: "Clean with mild soap and water, seal periodically for outdoor use.",
    whyChoose: "Kota Limestone offers durable, affordable luxury for any project.",
    seoTitle: "Kota Limestone | Durable Affordable Stone",
    metaDescription: "Explore Kota Limestone. Durable and affordable, perfect for both residential and commercial projects.",
    imageAlt: "Kota Limestone with grey/beige base",
    tags: ["Kota Limestone", "Limestone", "Natural Stone", "Indian Stone"]
  },
  {
    id: 403, name: "Bijolia Grey Limestone", slug: "bijolia-grey-limestone", categorySlug: "limestone", subcategorySlug: "bijolia-grey-limestone",
    image: "Limestone tile with layered texture.png", images: ["Limestone tile with layered texture.png"],
    category: getCategory("limestone"), subcategory: getSubcategory("limestone", "bijolia-grey-limestone"),
    description: "Bijolia Grey Limestone is a sophisticated grey limestone quarried in Bijolia, Rajasthan, perfect for creating elegant interiors.",
    features: ["Sophisticated grey base", "Elegant appearance", "Indian limestone", "Durable"],
    benefits: ["Adds elegance to interiors", "Perfect for modern designs", "Durable", "Versatile"],
    applications: ["Flooring", "Wall cladding", "Tabletops", "Fireplace surrounds", "Paving"],
    maintenance: "Clean with mild soap and water, seal periodically for outdoor use.",
    whyChoose: "Bijolia Grey Limestone offers a sophisticated, elegant look that complements any design.",
    seoTitle: "Bijolia Grey Limestone | Sophisticated Elegant Stone",
    metaDescription: "Discover Bijolia Grey Limestone. Sophisticated grey base, perfect for elegant interiors.",
    imageAlt: "Sophisticated Bijolia Grey Limestone with grey base",
    tags: ["Bijolia Grey Limestone", "Limestone", "Natural Stone", "Elegant Stone"]
  },
  {
    id: 404, name: "Chittor Black Limestone", slug: "chittor-black-limestone", categorySlug: "limestone", subcategorySlug: "chittor-black-limestone",
    image: "Black Granite.png", images: ["Black Granite.png"],
    category: getCategory("limestone"), subcategory: getSubcategory("limestone", "chittor-black-limestone"),
    description: "Chittor Black Limestone is a deep black limestone quarried in Chittor, Rajasthan, perfect for creating bold interiors.",
    features: ["Deep black base", "Bold appearance", "Indian limestone", "Durable"],
    benefits: ["Creates bold focal points", "Perfect for modern designs", "Durable", "Versatile"],
    applications: ["Flooring", "Wall cladding", "Tabletops", "Feature walls", "Paving"],
    maintenance: "Clean with mild soap and water, seal periodically for outdoor use.",
    whyChoose: "Chittor Black Limestone offers a bold, deep black look that makes a statement.",
    seoTitle: "Chittor Black Limestone | Bold Black Stone",
    metaDescription: "Explore Chittor Black Limestone. Deep black base, perfect for bold and modern interiors.",
    imageAlt: "Bold Chittor Black Limestone with deep black color",
    tags: ["Chittor Black Limestone", "Limestone", "Natural Stone", "Bold Stone"]
  },

  // Basalt Stone Product
  {
    id: 701,
    name: "Basalt",
    slug: "basalt",
    categorySlug: "basalt-stone",
    subcategorySlug: "basalt",
    image: "Basalt.png",
    images: ["Basalt.png"],
    category: getCategory("basalt-stone"),
    subcategory: getSubcategory("basalt-stone", "basalt"),
    description: "Basalt is a natural volcanic rock with a beautiful dark, textured surface, ideal for both interior and exterior applications.",
    features: ["Textured surface", "Natural volcanic rock", "Weather-resistant", "Durable"],
    benefits: ["Perfect for outdoor use", "Natural rustic look", "Long-lasting", "Low maintenance"],
    applications: ["Flooring", "Wall cladding", "Paving", "Landscaping", "Decorative elements"],
    maintenance: "Clean with mild soap and water, seal periodically for outdoor use.",
    whyChoose: "Basalt offers a natural, rustic look that adds character to any space.",
    seoTitle: "Basalt | Natural Volcanic Stone",
    metaDescription: "Discover Basalt. Natural volcanic rock with textured surface, perfect for interior and exterior use.",
    imageAlt: "Basalt with natural volcanic texture",
    tags: ["Basalt", "Basalt Stone", "Natural Stone", "Outdoor Stone"]
  }
];

// Helper functions to get categories, subcategories, products
export const getAllCategories = () => categories;
export const getCategoryBySlug = (slug) => categories.find(cat => cat.slug === slug);
export const findSubcategoryBySlug = (slug) => {
  for (const category of categories) {
    const found = category.subcategories.find(sub => sub.slug === slug);
    if (found) {
      return { ...found, category };
    }
  }
  return null;
};
export const getSubcategoryBySlug = (categorySlug, subcategorySlug) => {
  const category = getCategoryBySlug(categorySlug);
  return category?.subcategories.find(sub => sub.slug === subcategorySlug);
};

export const getAllProducts = () => productDefinitions;
export const getProductBySlug = (slug) => productDefinitions.find(p => p.slug === slug);
export const getProductsByCategory = (categorySlug) => productDefinitions.filter(p => p.categorySlug === categorySlug);
export const getProductsBySubcategory = (subcategorySlug) => productDefinitions.filter(p => p.subcategorySlug === subcategorySlug);
export const searchProducts = (query) => {
  if (!query || query.trim() === '') return [];
  
  const normalizedQuery = query.toLowerCase().trim();
  
  return productDefinitions.filter(product => {
    const searchFields = [
      product.name,
      product.categorySlug,
      product.subcategorySlug,
      product.category?.name || '',
      product.subcategory?.name || '',
      product.description,
      ...(product.tags || [])
    ].join(' ').toLowerCase();
    
    return searchFields.includes(normalizedQuery);
  });
};
